<a href="https://colab.research.google.com/github/dlskawns/RecSys_and_Retrieval_Study/blob/main/%EA%B0%84%EB%8B%A8%ED%9E%88MF%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
ratings

array([[0, 0, 0, 0, 3, 4, 1, 2, 0, 0],
       [0, 0, 0, 0, 5, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0, 0, 4, 2, 0],
       [0, 0, 1, 0, 2, 0, 0, 0, 0, 2]])

In [20]:
a = np.random.rand(5, 3) 
a

array([[0.770302  , 0.80847474, 0.8030573 ],
       [0.11476295, 0.88808986, 0.10667592],
       [0.23981016, 0.80759403, 0.10198876],
       [0.07828535, 0.34543636, 0.83598444],
       [0.06554275, 0.6360506 , 0.67026503]])

In [21]:
b = np.random.rand(10, 3) 
b

array([[0.79456481, 0.2994673 , 0.75812402],
       [0.83553903, 0.37388061, 0.41591966],
       [0.7343975 , 0.70654535, 0.7356914 ],
       [0.57297293, 0.94526627, 0.28584853],
       [0.65293073, 0.81104054, 0.40542651],
       [0.51364871, 0.14014905, 0.15721947],
       [0.03541432, 0.49180601, 0.68388763],
       [0.17620439, 0.78650459, 0.13184595],
       [0.60086037, 0.51830006, 0.00414951],
       [0.08791205, 0.52267979, 0.00458374]])

In [17]:
ratings.nonzero()

(array([0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 4]),
 array([4, 5, 6, 7, 4, 6, 5, 9, 7, 8, 2, 4, 9]))

In [15]:
for u, i in zip(*ratings.nonzero()):
  print(u, i)

0 4
0 5
0 6
0 7
1 4
1 6
2 5
2 9
3 7
3 8
4 2
4 4
4 9


In [22]:
a[0,:]

array([0.770302  , 0.80847474, 0.8030573 ])

In [23]:
b[4,:]

array([0.65293073, 0.81104054, 0.40542651])

In [24]:
ratings[0,4]-a[0,:].dot(b[4,:])

1.515759647450651

In [27]:
a[0,0] = 0.0003 * (2 * )

0.770302002065551

In [1]:
import numpy as np

def mf(R, k, n_epoch=5000, lr=.0003, l2=.04):
  tol = .001  # Tolerant loss.
  m, n = R.shape  # 5, 10               # 5명의 유저, 10개의 아이템
  # Initialize the embedding weights.
  P = np.random.rand(m, k)  # 5, 3      # 행렬 P를 임의의 복소수로 초기화
  Q = np.random.rand(n, k)  # 10, 3     # 행렬 Q를 임의의 복소수로 초기화
  for epoch in range(n_epoch):          
    # Update weights by gradients.
    for u, i in zip(*R.nonzero()):      # u: 행렬 내 0이 아닌 수의 열, i: 행렬 내 0이 아닌 수의 행
      err_ui = R[u,i] - P[u,:].dot(Q[i,:])    # 오차 구하기 = 기존 행렬 점수에서 P행렬과 Q행렬의 내적 값을 제외한 값
      for j in range(k):                      # 
        P[u][j] += lr * (2 * err_ui * Q[i][j] - l2/2 * P[u][j])   # P행렬 오차 업데이트 = 기존 P행렬에서 학습률 * (2 * 오차* Q행렬) - 레귤러 텀 * P행렬의 유저
        Q[i][j] += lr * (2 * err_ui * P[u][j] - l2/2 * Q[i][j])
    # compute the loss.
    E = (R - P.dot(Q.T))**2
    obj = E[R.nonzero()].sum() + lr*((P**2).sum() +(Q**2).sum())
    if obj < tol:
        break
  return P, Q

In [45]:
np.random.seed(777)

# Make missing more prevail.
stars = np.arange(6)
p = np.array([10, 1, 1, 1, 1, 1]) # 확률, 0이 제일 높고 나머지 평점은 균일 - sparse하게 만듦
m = 5
n = 10

# A 5-star rating matrix.
ratings = np.random.choice(stars, size=m*n, p=p / p.sum()).reshape((m, n))
print(ratings)

[[0 0 0 0 3 4 1 2 0 0]
 [0 0 0 0 5 0 1 0 0 0]
 [0 0 0 0 0 4 0 0 0 3]
 [0 0 0 0 0 0 0 4 2 0]
 [0 0 1 0 2 0 0 0 0 2]]


In [47]:
P, Q = mf(ratings, k=3)

print(P)  # User embeddings.

[[0.63030098 1.32632817 0.22731696]
 [0.91776555 1.65371568 1.13847576]
 [0.94394792 1.20334036 0.08460967]
 [1.48581284 1.84234102 0.85833273]
 [0.90108838 0.48804721 0.31216772]]


In [48]:
print(Q)  # Item embeddings.

[[ 0.69258857  0.83594341  0.42432199]
 [ 0.8487743   0.54679121  0.35410346]
 [ 0.73827766  0.1010681   0.87686572]
 [ 0.33625828  0.89183268  0.296849  ]
 [ 0.87169152  1.62740441  1.29970871]
 [ 1.50389245  2.12570844  0.65550343]
 [ 0.37660684  0.52827304 -0.1436639 ]
 [ 1.11657344  0.99507904  0.50060044]
 [ 0.32235812  0.39279822  0.93554762]
 [ 1.48046418  1.27550157  0.17612006]]


In [50]:
l2 = np.sqrt(pow(P, 2).sum(axis=1))

np.outer(l2, l2)

array([[2.20809874, 3.28031986, 2.27611408, 3.74115548, 1.59185803],
       [3.28031986, 4.87319621, 3.38136248, 5.557807  , 2.36484149],
       [2.27611408, 3.38136248, 2.34622448, 3.85639307, 1.64089151],
       [3.74115548, 5.557807  , 3.85639307, 6.33859532, 2.69706616],
       [1.59185803, 2.36484149, 1.64089151, 2.69706616, 1.14759903]])

In [55]:
l2

array([1.48596727, 2.2075317 , 1.53173904, 2.51765671, 1.07126049])

In [51]:
P.dot(P.T)

array([[2.20809874, 3.03063306, 2.21022872, 3.57517167, 1.28622867],
       [3.03063306, 4.87319621, 2.95263175, 5.38752708, 1.98947458],
       [2.21022872, 2.95263175, 2.34622448, 3.69211649, 1.46427981],
       [3.57517167, 5.38752708, 3.69211649, 6.33859532, 2.50594186],
       [1.28622867, 1.98947458, 1.46427981, 2.50594186, 1.14759903]])

In [53]:
P.dot(P.T) / np.outer(l2, l2)  # 유저 간 유사도를 구하기 위해 


array([[1.        , 0.9238834 , 0.97105358, 0.95563301, 0.80800464],
       [0.9238834 , 1.        , 0.8732077 , 0.96936203, 0.84127185],
       [0.97105358, 0.8732077 , 1.        , 0.95740149, 0.89236845],
       [0.95563301, 0.96936203, 0.95740149, 1.        , 0.92913622],
       [0.80800464, 0.84127185, 0.89236845, 0.92913622, 1.        ]])

In [56]:
# User similarity.
l2 = np.sqrt(pow(P, 2).sum(axis=1)) # 유저 행렬의 각 유저 별 벡터를 제곱 후 더한 뒤 제곱근 처리한 값
user_sim = P.dot(P.T) / np.outer(l2, l2)  # 유저 간 유사도를 구하기 위해 
print(np.round(user_sim, 2))

[[1.   0.92 0.97 0.96 0.81]
 [0.92 1.   0.87 0.97 0.84]
 [0.97 0.87 1.   0.96 0.89]
 [0.96 0.97 0.96 1.   0.93]
 [0.81 0.84 0.89 0.93 1.  ]]


In [57]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(P)

array([[1.        , 0.9238834 , 0.97105358, 0.95563301, 0.80800464],
       [0.9238834 , 1.        , 0.8732077 , 0.96936203, 0.84127185],
       [0.97105358, 0.8732077 , 1.        , 0.95740149, 0.89236845],
       [0.95563301, 0.96936203, 0.95740149, 1.        , 0.92913622],
       [0.80800464, 0.84127185, 0.89236845, 0.92913622, 1.        ]])

In [58]:
predictions = P.dot(Q.T)

In [61]:
mask = np.zeros_like(ratings)
mask[ratings.nonzero()] = 1

In [59]:
np.zeros_like(ratings)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [62]:
mask

array([[0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 1]])

In [65]:
predictions*(1-mask)

array([[1.64173013, 1.34070158, 0.79871305, 1.46228554, 0.        ,
        0.        , 0.        , 0.        , 0.93682782, 2.66490676],
       [2.50112696, 2.08635122, 1.84299407, 2.12139934, 0.        ,
        5.64181282, 0.        , 3.24025191, 2.01052404, 3.66854438],
       [1.69559372, 1.48913524, 0.89270631, 1.41570485, 2.89112072,
        0.        , 0.97903415, 2.29376158, 0.8561156 , 0.        ],
       [2.93335929, 2.57243423, 2.03578689, 2.39747202, 5.40898689,
        6.71342263, 1.40951494, 0.        , 0.        , 4.70077117],
       [1.16452299, 1.14222026, 0.        , 0.83092156, 0.        ,
        2.5972131 , 0.552331  , 1.6480482 , 0.774225  , 0.        ]])